export const AuthFailureResponse = "authentication failed"
export const InternalResponse = "Internal Error"
export const AccessTokenErrorResponse = "token is not valid"
export const NotFoundResponse = "not Found"
export const ForbiddenResponse = "Forbidden"
export const DuplicateResponse = "Duplicate"
export const UploadingResponse = "Error uploading icon"
